[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

# Thank you bunco :)
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''--check the hand first'''
position = 'after'
payload = '''
if G.jokers ~= nil then
    SMODS.calculate_context({abn_play_cards = true})
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "self.facing='back'"
position = "after"
payload = '''
if self.ability.set == "Joker" then
    self.ability.joker_flipped = true
    self:set_cost()
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "self.facing='front'"
position = "after"
payload = '''
if self.ability.set == "Joker" then
    self.ability.joker_flipped = nil
    self:set_cost()
end
'''
match_indent = true

# For Inkblot Test/ Joker AI
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = "if self.highlighted[i].ability.forced_selection and self == G.hand then"
position = "after"
payload = '''
elseif (self.highlighted[i].ability.abn_forced_selection or self.highlighted[i].ability.abn_inkblot_forced_selection) and self == G.hand then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = "if (not force) and  card and card.ability.forced_selection and self == G.hand then return end"
position = "after"
payload = '''
if (not force) and card and (card.ability.abn_forced_selection or card.ability.abn_inkblot_forced_selection) and self == G.hand then return end
'''
match_indent = true
