[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

# Thank you bunco :)
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''--check the hand first'''
position = 'after'
payload = '''
if G.jokers ~= nil then
    SMODS.calculate_context({abn_play_cards = true})
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "self.facing='back'"
position = "after"
payload = '''
if self.ability.set == "Joker" then
    self.ability.joker_flipped = true
    self:set_cost()
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "self.facing='front'"
position = "after"
payload = '''
if self.ability.set == "Joker" then
    self.ability.joker_flipped = nil
    self:set_cost()
end
'''
match_indent = true

# For Inkblot Test/ Joker AI
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = "if self.highlighted[i].ability.forced_selection and self == G.hand then"
position = "after"
payload = '''
elseif (self.highlighted[i].ability.abn_forced_selection or self.highlighted[i].ability.abn_inkblot_forced_selection) and self == G.hand then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = "if (not force) and  card and card.ability.forced_selection and self == G.hand then return end"
position = "after"
payload = '''
if (not force) and card and (card.ability.abn_forced_selection or card.ability.abn_inkblot_forced_selection) and self == G.hand then return end
'''
match_indent = true

# G.GAME Variables
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''unused_discards = 0,'''
position = "after"
payload = '''
abn = {
    legendary_pool = {in_shop = false, rate = 1.00},
},
'''
match_indent = true

# borrowed from All in Jest, ty
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
if _type == 'Joker' then 
'''
position = "before"
match_indent = true
payload = '''
if G.GAME.abn.legendary_pool ~= nil and _type == 'Joker' then
    if G.GAME.abn.legendary_pool.in_shop then
        local rary = _rarity or pseudorandom('rarity'..G.GAME.round_resets.ante..(_append or '')) 
        if type(rary) == "number" and (_rarity == nil or _rarity == 4 or _rarity == "Legendary") then
            rary = (rary > G.GAME.abn.legendary_pool.rate and 4) or 1 
            if rary ~= 1 then
                _legendary = true
            end
        end
    end
end
'''
