-- vanilla jokers list
local vanilla_jokers = {
    j_joker = true,
    j_greedy_joker = true,
    j_lusty_joker = true,
    j_wrathful_joker = true,
    j_gluttenous_joker = true,
    j_jolly = true,
    j_zany = true,
    j_mad = true,
    j_crazy = true,
    j_droll = true,
    j_sly = true,
    j_wily = true,
    j_clever = true,
    j_devious = true,
    j_crafty = true,
    j_half = true,
    j_stencil = true,
    j_four_fingers = true,
    j_mime = true,
    j_credit_card = true,
    j_ceremonial = true,
    j_banner = true,
    j_mystic_summit = true,
    j_marble = true,
    j_loyalty_card = true,
    j_8_ball = true,
    j_misprint = true,
    j_dusk = true,
    j_raised_fist = true,
    j_chaos = true,
    j_fibonacci = true,
    j_steel_joker = true,
    j_scary_face = true,
    j_abstract = true,
    j_delayed_grat = true,
    j_hack = true,
    j_pareidolia = true,
    j_gros_michel = true,
    j_even_steven = true,
    j_odd_todd = true,
    j_scholar = true,
    j_business = true,
    j_supernova = true,
    j_ride_the_bus = true,
    j_space = true,
    j_egg = true,
    j_burglar = true,
    j_blackboard = true,
    j_runner = true,
    j_ice_cream = true,
    j_dna = true,
    j_splash = true,
    j_blue_joker = true,
    j_sixth_sense = true,
    j_constellation = true,
    j_hiker = true,
    j_faceless = true,
    j_green_joker = true,
    j_superposition = true,
    j_todo_list = true,
    j_cavendish = true,
    j_card_sharp = true,
    j_red_card = true,
    j_madness = true,
    j_square = true,
    j_seance = true,
    j_riff_raff = true,
    j_vampire = true,
    j_shortcut = true,
    j_hologram = true,
    j_vagabond = true,
    j_baron = true,
    j_cloud_9 = true,
    j_rocket = true,
    j_obelisk = true,
    j_midas_mask = true,
    j_luchador = true,
    j_photograph = true,
    j_gift = true,
    j_turtle_bean = true,
    j_erosion = true,
    j_reserved_parking = true,
    j_mail = true,
    j_to_the_moon = true,
    j_hallucination = true,
    j_fortune_teller = true,
    j_juggler = true,
    j_drunkard = true,
    j_stone = true,
    j_golden = true,
    j_lucky_cat = true,
    j_baseball = true,
    j_bull = true,
    j_diet_cola = true,
    j_trading = true,
    j_flash = true,
    j_popcorn = true,
    j_trousers = true,
    j_ancient = true,
    j_ramen = true,
    j_walkie_talkie = true,
    j_selzer = true,
    j_castle = true,
    j_smiley = true,
    j_campfire = true,
    j_ticket = true,
    j_mr_bones = true,
    j_acrobat = true,
    j_sock_and_buskin = true,
    j_swashbuckler = true,
    j_troubadour = true,
    j_certificate = true,
    j_smeared = true,
    j_throwback = true,
    j_hanging_chad = true,
    j_rough_gem = true,
    j_bloodstone = true,
    j_arrowhead = true,
    j_onyx_agate = true,
    j_glass = true,
    j_ring_master = true,
    j_flower_pot = true,
    j_blueprint = true,
    j_wee = true,
    j_merry_andy = true,
    j_oops = true,
    j_idol = true,
    j_seeing_double = true,
    j_matador = true,
    j_hit_the_road = true,
    j_duo = true,
    j_trio = true,
    j_family = true,
    j_order = true,
    j_tribe = true,
    j_stuntman = true,
    j_invisible = true,
    j_brainstorm = true,
    j_satellite = true,
    j_shoot_the_moon = true,
    j_drivers_license = true,
    j_cartomancer = true,
    j_astronomer = true,
    j_burnt = true,
    j_bootstraps = true,
    j_caino = true,
    j_triboulet = true,
    j_yorick = true,
    j_chicot = true,
    j_perkeo = true
}

SMODS.Joker {
  key = 'rom_hack_balatro',

  set_badges = function(self, card, badges)
    badges[#badges + 1] = create_badge(localize("k_abn_plagued"), G.C.GREEN, G.C.WHITE, 1.0)
  end,

  rarity = "abn_SuperRare",
  atlas = 'ABNJokerSheet12',
  pos = { x = 4, y = 0 },
  cost = 20,
  discovered = false,
  blueprint_compat = true,

  config = { extra = { xmult = 8, xchips = 3, dollars = 10 } },
  pools = { ["Plagued"] = true, },
  
  loc_vars = function(self, info_queue, card)
    return { 
      vars = { 
        card.ability.extra.xmult,
		card.ability.extra.xchips,
		card.ability.extra.dollars
      } 
    }
  end,
  
  in_pool = function(self)
    return G.GAME.modifiers.Toxic or G.GAME.modifiers.Menacing or G.GAME.modifiers.Honor
  end,

  calculate = function(self, card, context)
    if context.other_joker and context.other_joker ~= card and vanilla_jokers[context.other_joker.config.center.key] then
        return {
            xmult = card.ability.extra.xmult,
			xchips = card.ability.extra.xchips,
			dollars = card.ability.extra.dollars,
			card = card
		}
    end
  end,

  abn_artist_credits = {
    artist = "Dogg-Fly & Vega",
  },
}