[manifest]
version = "0.1.0"
dump_lua = true
priority = -11

# context.final_scoring_step
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''local nu_chip, nu_mult = G.GAME.selected_back:trigger_effect{context = 'final_scoring_step', chips = hand_chips, mult = mult}'''
match_indent = true
position = "before"
payload = '''
-- context.final_scoring_step calculations


if G.GAME and G.GAME.blind and G.GAME.blind.config.blind.key == 'bl_abn_mint_£' and not G.GAME.blind.disabled then
	
	if G.GAME.dollars * 3 < mult then
		mult = G.GAME.dollars * 3
	end
	
elseif G.GAME and G.GAME.blind and G.GAME.blind.config.blind.key == 'bl_abn_hazard_£' and not G.GAME.blind.disabled then
	if G.GAME.dollars * 2 < mult then
		mult = G.GAME.dollars * 2
	end
	
elseif G.GAME and G.GAME.blind and G.GAME.blind.name == 'No Sweat Insurance' and not G.GAME.blind.disabled then
	if to_big(G.GAME.dollars) < to_big(mult) then
		mult = G.GAME.dollars
	end
end
'''


# Borrowed patch from Bunco, check them out! 
# function Card:highlight (Glue Deck 1/2)
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'self.highlighted = is_higlighted'
position = 'after'
match_indent = true
payload = '''

if G.GAME.selected_back_key and G.GAME.selected_back_key.key == "b_abn_glue_deck" and is_higlighted and self.area == G.hand then
    self.ability.forced_selection = true
end

'''

# Borrowed patch from Bunco, check them out! 
# function CardArea:remove_from_highlighted (Glue Deck 2/2)
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = 'function CardArea:remove_from_highlighted(card, force)'
position = 'after'
match_indent = true
payload = '''

if G.GAME.selected_back_key and G.GAME.selected_back_key.key == "b_abn_glue_deck" and not force and card.area == G.hand then
    if G.GAME.blind.disabled then
        card.ability.forced_selection = false
    elseif not G.GAME.blind.disabled and card.ability.forced_selection == true then
        local _deck = G.deck.cards and #G.deck.cards > 0 and G.deck.cards[1] or G.deck
				SMODS.calculate_effect({message = localize("k_nope_ex"),colour = G.C.PURPLE},_deck)
    end
end

'''
