[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# generate_card_ui
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
position = 'before'
pattern = '''if main_end then'''
payload = '''
if abn_extra_chips then
    desc_nodes[#desc_nodes+1] = abn_extra_chips 
end
'''
match_indent = true
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
position = 'at'
pattern = '''function generate_card_ui(_c, full_UI_table, specific_vars, card_type, badges, hide_desc, main_start, main_end, card)'''
payload = '''
function generate_card_ui(_c, full_UI_table, specific_vars, card_type, badges, hide_desc, main_start, main_end, card, abn_extra_chips)
'''
match_indent = true

# generate_UIBox_ability_table
[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'after'
pattern = '''if self.sticker or ((self.sticker_run and self.sticker_run~='NONE') and G.SETTINGS.run_stake_stickers)  then loc_vars = loc_vars or {}; loc_vars.sticker=(self.sticker or self.sticker_run) end'''
payload = '''
local abn_extra_chips = nil
if self.ability.perma_bonus and (self.ability.perma_bonus>0 or self.ability.perma_bonus<0) then 
local operation = ""
if self.ability.perma_bonus>0 then
    operation = "+"
end
abn_extra_chips = (self.area and self.area == G.jokers) and {
                {n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={
                    {n=G.UIT.C, config={ref_table = self, align = "m", colour = G.C.CLEAR, r = 0.05, padding = 0.06}, nodes={
                        {n=G.UIT.T, config={text = operation .. self.ability.perma_bonus ,colour = G.C.BLUE, scale = 0.32}},
                        {n=G.UIT.T, config={text = "", colour = G.C.BLUE, scale = 0.1}},
                        {n=G.UIT.T, config={text = localize("abn_joker_chip") ,colour = G.C.L_BLACK, scale = 0.32,padding = 0.1}},
                    }}
                }}
            } or nil
end
'''
match_indent = true
[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'at'
pattern = '''return generate_card_ui(self.config.center, nil, loc_vars, card_type, badges, hide_desc, main_start, main_end, self)'''
payload = '''
   return generate_card_ui(self.config.center, nil, loc_vars, card_type, badges, hide_desc, main_start, main_end, self, abn_extra_chips)
'''
match_indent = true