[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# ---------------------------------------------------------
# common_events.lua: Updating the UI function and Display
# ---------------------------------------------------------

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
position = 'at'
pattern = '''function generate_card_ui(_c, full_UI_table, specific_vars, card_type, badges, hide_desc, main_start, main_end, card)'''
payload = '''
function generate_card_ui(_c, full_UI_table, specific_vars, card_type, badges, hide_desc, main_start, main_end, card, abn_extra_chips, abn_extra_mult, abn_extra_xmult, abn_extra_xchips, abn_extra_dollars, abn_extra_rep)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
position = 'before'
pattern = '''if main_end then'''
payload = '''
if abn_extra_chips then desc_nodes[#desc_nodes+1] = abn_extra_chips end
if abn_extra_mult then desc_nodes[#desc_nodes+1] = abn_extra_mult end
if abn_extra_xmult then desc_nodes[#desc_nodes+1] = abn_extra_xmult end
if abn_extra_xchips then desc_nodes[#desc_nodes+1] = abn_extra_xchips end
if abn_extra_dollars then desc_nodes[#desc_nodes+1] = abn_extra_dollars end
if abn_extra_rep then desc_nodes[#desc_nodes+1] = abn_extra_rep end
'''
match_indent = true

# ---------------------------------------------------------
# card.lua: Calculating UI elements and passing them
# ---------------------------------------------------------

[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'after'
pattern = '''if self.sticker or ((self.sticker_run and self.sticker_run~='NONE') and G.SETTINGS.run_stake_stickers)  then loc_vars = loc_vars or {}; loc_vars.sticker=(self.sticker or self.sticker_run) end'''
payload = '''
local abn_extra_chips = nil
local abn_extra_mult = nil
local abn_extra_xmult = nil
local abn_extra_xchips = nil
local abn_extra_dollars = nil
local abn_extra_rep = nil

-- Logic for Chips
if self.ability.abn_perma_bonus and self.ability.abn_perma_bonus ~= 0 then 
    local chip_op = self.ability.abn_perma_bonus > 0 and "+" or ""
    abn_extra_chips = (self.area and self.area == G.jokers) and {{n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={{n=G.UIT.C, config={ref_table = self, align = "m", colour = G.C.CLEAR, r = 0.05, padding = 0.06}, nodes={{n=G.UIT.T, config={text = chip_op .. self.ability.abn_perma_bonus, colour = G.C.BLUE, scale = 0.32}},{n=G.UIT.T, config={text = "", colour = G.C.BLUE, scale = 0.1}},{n=G.UIT.T, config={text = localize("abn_joker_chip"), colour = G.C.L_BLACK, scale = 0.32, padding = 0.1}}}}}}} or nil
end

-- Logic for Mult
if self.ability.abn_perma_mult and self.ability.abn_perma_mult ~= 0 then 
    local mult_op = self.ability.abn_perma_mult > 0 and "+" or ""
    abn_extra_mult = (self.area and self.area == G.jokers) and {{n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={{n=G.UIT.C, config={ref_table = self, align = "m", colour = G.C.CLEAR, r = 0.05, padding = 0.06}, nodes={{n=G.UIT.T, config={text = mult_op .. self.ability.abn_perma_mult, colour = G.C.RED, scale = 0.32}},{n=G.UIT.T, config={text = "", colour = G.C.RED, scale = 0.1}},{n=G.UIT.T, config={text = localize("abn_joker_mult"), colour = G.C.L_BLACK, scale = 0.32, padding = 0.1}}}}}}} or nil
end

-- Logic for XMult
if self.ability.abn_perma_xmult and self.ability.abn_perma_xmult ~= 1 then 
    abn_extra_xmult = (self.area and self.area == G.jokers) and {{n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={{n=G.UIT.C, config={ref_table = self, align = "m", colour = G.C.CLEAR, r = 0.05, padding = 0.06}, nodes={{n=G.UIT.T, config={text = "X" .. self.ability.abn_perma_xmult, colour = G.C.MULT, scale = 0.32}},{n=G.UIT.T, config={text = "", colour = G.C.MULT, scale = 0.1}},{n=G.UIT.T, config={text = localize("abn_joker_xmult"), colour = G.C.L_BLACK, scale = 0.32, padding = 0.1}}}}}}} or nil
end

-- Logic for XChips
if self.ability.abn_perma_xchips and self.ability.abn_perma_xchips ~= 1 then 
    abn_extra_xchips = (self.area and self.area == G.jokers) and {{n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={{n=G.UIT.C, config={ref_table = self, align = "m", colour = G.C.CLEAR, r = 0.05, padding = 0.06}, nodes={{n=G.UIT.T, config={text = "X" .. self.ability.abn_perma_xchips, colour = G.C.CHIPS, scale = 0.32}},{n=G.UIT.T, config={text = "", colour = G.C.CHIPS, scale = 0.1}},{n=G.UIT.T, config={text = localize("abn_joker_xchips"), colour = G.C.L_BLACK, scale = 0.32, padding = 0.1}}}}}}} or nil
end

-- Logic for Dollars
if self.ability.abn_perma_dollars and self.ability.abn_perma_dollars ~= 0 then 
    local dol_op = self.ability.abn_perma_dollars > 0 and "+" or ""
    abn_extra_dollars = (self.area and self.area == G.jokers) and {{n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={{n=G.UIT.C, config={ref_table = self, align = "m", colour = G.C.CLEAR, r = 0.05, padding = 0.06}, nodes={{n=G.UIT.T, config={text = dol_op .. "$" .. self.ability.abn_perma_dollars, colour = G.C.MONEY, scale = 0.32}},{n=G.UIT.T, config={text = "", colour = G.C.MONEY, scale = 0.1}},{n=G.UIT.T, config={text = localize("abn_joker_dollars"), colour = G.C.L_BLACK, scale = 0.32, padding = 0.1}}}}}}} or nil
end

-- Logic for Repetitions
if self.ability.abn_perma_rep and self.ability.abn_perma_rep ~= 0 then 
    local rep_op = self.ability.abn_perma_rep > 0 and "+" or ""
    abn_extra_rep = (self.area and self.area == G.jokers) and {{n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={{n=G.UIT.C, config={ref_table = self, align = "m", colour = G.C.CLEAR, r = 0.05, padding = 0.06}, nodes={{n=G.UIT.T, config={text = rep_op .. self.ability.abn_perma_rep, colour = G.C.ORANGE, scale = 0.32}},{n=G.UIT.T, config={text = "", colour = G.C.ORANGE, scale = 0.1}},{n=G.UIT.T, config={text = localize("abn_joker_rep"), colour = G.C.L_BLACK, scale = 0.32, padding = 0.1}}}}}}} or nil
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'at'
pattern = '''return generate_card_ui(self.config.center, nil, loc_vars, card_type, badges, hide_desc, main_start, main_end, self)'''
payload = '''
return generate_card_ui(self.config.center, nil, loc_vars, card_type, badges, hide_desc, main_start, main_end, self, abn_extra_chips, abn_extra_mult, abn_extra_xmult, abn_extra_xchips, abn_extra_dollars, abn_extra_rep)
'''
match_indent = true