[manifest]
version = "0.1.0"
dump_lua = true
priority = 10

# Thank you bunco :)
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''--check the hand first'''
position = 'after'
payload = '''
if G.jokers ~= nil then
    SMODS.calculate_context({abn_play_cards = true})
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "self.facing='back'"
position = "after"
payload = '''
if self.ability.set == "Joker" then
    self.ability.joker_flipped = true
    self:set_cost()
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "self.facing='front'"
position = "after"
payload = '''
if self.ability.set == "Joker" then
    self.ability.joker_flipped = nil
    self:set_cost()
end
'''
match_indent = true

# For Inkblot Test/ Joker AI
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = "if self.highlighted[i].ability.forced_selection and self == G.hand then"
position = "after"
payload = '''
elseif (self.highlighted[i].ability.abn_forced_selection or self.highlighted[i].ability.abn_inkblot_forced_selection) and self == G.hand then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = "if (not force) and  card and card.ability.forced_selection and self == G.hand then return end"
position = "after"
payload = '''
if (not force) and card and (card.ability.abn_forced_selection or card.ability.abn_inkblot_forced_selection) and self == G.hand then return end
'''
match_indent = true

# G.GAME Variables
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''unused_discards = 0,'''
position = "after"
payload = '''
abn = {
    legendary_pool = {in_shop = false, rate = 1.00},
    cthonian = false
},
'''
match_indent = true

# borrowed from All in Jest, ty
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
if _type == 'Joker' then 
'''
position = "before"
match_indent = true
payload = '''
if G.GAME.abn.legendary_pool ~= nil and _type == 'Joker' then
    if G.GAME.abn.legendary_pool.in_shop then
        local rary = _rarity or pseudorandom('rarity'..G.GAME.round_resets.ante..(_append or '')) 
        if type(rary) == "number" and (_rarity == nil or _rarity == 4 or _rarity == "Legendary") then
            rary = (rary > G.GAME.abn.legendary_pool.rate and 4) or 1 
            if rary ~= 1 then
                _legendary = true
            end
        end
    end
end
'''

# Add 2% to blind requirements for every chthonian edition you have in Jokers/full deck
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = "self.chips = get_blind_amount(G.GAME.round_resets.ante)*self.mult*G.GAME.starting_params.ante_scaling"
position = "after"
payload = '''
if G.GAME.abn.cthonian then
    local base_score = get_blind_amount(G.GAME.round_resets.ante) * self.mult * G.GAME.starting_params.ante_scaling
    local tally = 0
    if G.playing_cards then
      for _, c in ipairs(G.playing_cards) do
        if c.edition and c.edition.key == "e_abn_chthonian" then tally = tally + 1 end
      end
    end
    if G.jokers and G.jokers.cards then
      for _, c in ipairs(G.jokers.cards) do
        if c.edition and c.edition.key == "e_abn_chthonian" then tally = tally + 1 end
      end
    end
    local percent =  1 + (0.02 * tally)
    if G.GAME.blind_on_deck == 'Small' then
        self.chips = math.floor(base_score * percent)
    elseif G.GAME.blind_on_deck == 'Big' then
        self.chips = math.floor(base_score * percent)
    elseif G.GAME.blind_on_deck == 'Boss' then
        self.chips = math.floor(base_score * percent)
    else
        self.chips = base_score
    end
else
    self.chips = get_blind_amount(G.GAME.round_resets.ante) * self.mult * G.GAME.starting_params.ante_scaling
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling"
position = "after"
payload = '''
if G.GAME.abn.cthonian then
    local tally = 0
    if G.playing_cards then
      for _, c in ipairs(G.playing_cards) do
        if c.edition and c.edition.key == "e_abn_chthonian" then tally = tally + 1 end
      end
    end
    if G.jokers and G.jokers.cards then
      for _, c in ipairs(G.jokers.cards) do
        if c.edition and c.edition.key == "e_abn_chthonian" then tally = tally + 1 end
      end
    end
    local percent =  1 + (0.02 * tally)
    if type == 'Small' then
        blind_amt = math.floor(blind_amt * percent)
    elseif type == 'Big' then
        blind_amt = math.floor(blind_amt * percent)
    elseif type == 'Boss' then
        blind_amt = math.floor(blind_amt * percent)
    else
        blind_amt = blind_amt
    end
end
'''
match_indent = true

# G.FUNCS.use_card()
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
match_indent = true
position = 'before'
pattern = "if not dont_dissolve then card:start_dissolve() end"
payload = '''
local abnmove = false
if not dont_dissolve and card.ability.set == "Tarot" then
    if G.GAME.used_vouchers["v_abn_tarot_master"] and pseudorandom("vccc") < 1/6 then
        dont_dissolve = true
        abnmove = true
    end
elseif not dont_dissolve and card.ability.set == "Planet" then
    if G.GAME.used_vouchers["v_abn_planet_master"] and pseudorandom("vccc") < 1/6 then
        dont_dissolve = true
        abnmove = true
    end
end

if dont_dissolve and abnmove then
    G.E_MANAGER:add_event(Event{
        func = function()
            draw_card(G.play, G.consumeables, 100, 'up', true, card)
            ABN.msg(card, localize("abn_kept"))
            return true
        end
    })
end
'''

# G.FUNCS.reroll_boss()
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
match_indent = true
position = 'at'
pattern = '''    if ((G.GAME.dollars-G.GAME.bankrupt_at) - 10 >= 0) and
      (G.GAME.used_vouchers["v_retcon"] or
      (G.GAME.used_vouchers["v_directors_cut"] and not G.GAME.round_resets.boss_rerolled)) then
'''
payload = '''
    if ((G.GAME.dollars-G.GAME.bankrupt_at) - (G.GAME.abn_boss_reroll_cost or 10) >= 0) and
      (G.GAME.used_vouchers["v_retcon"] or
      (G.GAME.used_vouchers["v_directors_cut"] and not G.GAME.round_resets.boss_rerolled) or next(SMODS.find_card("j_abn_bad_director"))) then 
'''
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
match_indent = true
position = 'at'
pattern = "if not G.from_boss_tag then ease_dollars(-10) end"
payload = '''
if not G.from_boss_tag then ease_dollars(-(G.GAME.abn_boss_reroll_cost or 10)) end
'''
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
match_indent = true
position = 'after'
pattern = "G.GAME.round_resets.blind_choices.Boss = get_new_boss()"
payload = '''
SMODS.calculate_context({abn_reroll_boss = true, cost = G.GAME.current_round.reroll_cost})
'''


# UI Definitions Blind Reroll button
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
match_indent = true
position = 'at'
pattern = '''        UIBox_button({label = {localize('b_reroll_boss'), localize('$')..'10'}, button = "reroll_boss", func = 'reroll_boss_button'}) or nil''' 
payload = '''
        UIBox_button({label = {localize('b_reroll_boss'), localize('$')..(G.GAME.abn_boss_reroll_cost or 10)}, button = "reroll_boss", func = 'reroll_boss_button'}) or nil
'''

# UI Definitions Blind Reroll button
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
match_indent = true
position = 'at'
pattern = '''        (G.GAME.used_vouchers["v_retcon"] or G.GAME.used_vouchers["v_directors_cut"]) and''' 
payload = '''
        (G.GAME.used_vouchers["v_retcon"] or G.GAME.used_vouchers["v_directors_cut"] or next(SMODS.find_card("j_abn_bad_director"))) and
'''

# function Card:flip(), Credits to Bunco for the patch!
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "self.facing='back'"
position = "after"
payload = '''
if self.config.center.key == 'j_abn_giacomo' and not self.ability.abn_perma_flipped and not self.shadowy_flipped then
    self:flip()
    self:calculate_joker({flip = true})
end
'''
match_indent = true