[manifest]
version = "0.1.0"
dump_lua = true
priority = 10

# Ranks Tab in Run Info
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = """tab_definition_function = create_UIBox_current_hands,
},"""
position = "after"
payload = '''
{
	label = localize('b_abn_planet_ranks'),
	tab_definition_function = create_UIBox_current_ranks,
},
'''
match_indent = true

# Add card descriptions for rank levels [1/2]
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''SMODS.localize_perma_bonuses(specific_vars, desc_nodes)'''
position = "after"
payload = '''
if ABN then
  ABN.localize_perma_bonuses(specific_vars, desc_nodes, card)
end
'''
match_indent = true

# Add card descriptions for rank levels [2/2]
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''SMODS.localize_perma_bonuses(specific_vars, desc_nodes)'''
position = "after"
payload = '''
if ABN then
  ABN.localize_perma_bonuses(specific_vars, desc_nodes, card)
end
'''
match_indent = true