[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
position = 'before'
pattern = '''
return self.base.suit == suit
'''
payload = '''
if G.jokers and G.jokers.cards and self and self.area and self.area.cards then
    for _, j in ipairs(G.jokers.cards) do
        if self == self.area.cards[1] and j.ability["abn_stk_wild"] then
        return true
        end
    end
end
'''