return {
  description = {
    Other = {
    },
  },
  misc = {
    labels = {
      -- Stickers

      abn_pump_up = "Pump Up",
      abn_immortal = "Immortal",
      abn_bullseye = "Bullseye",
      abn_shovel = "Shovel",
      abn_downgrade = "Downgrade",
      abn_vessel = "Vessel",
      abn_weight = "Weight",
      abn_crown = "Crown",
      abn_flip = "Flip",
      abn_fragile = "Fragile",
      abn_possibility = "Possibility",
      abn_question_mark = "Question Mark?",
      abn_square = "Square",
      abn_lightning_bolt = "Lightning Bolt",
      abn_top_hat = "Top Hat",
      abn_cat_eye = "Cat Eye",
      abn_eraser = "Eraser",
      abn_lucky = "Lucky",
      abn_negative_plus = "Negative+",
      abn_glove_hand = "Glove Hand",
      abn_spicy = "Spicy",
      abn_x = "X",
      abn_spade = "Spade",
      abn_club = "Club",
      abn_diamond = "Diamond",
      abn_heart = "Heart",
      abn_daytime = "Daytime",
      abn_nighttime = "Nightime",
      abn_even_legacy = "Even Legacy",
      abn_odd_legacy = "Odd Legacy",
      abn_jimbo_legacy = "Jimbo Legacy",
      abn_rejok_legacy = "Rejok Legacy",
      abn_obmij_legacy = "Obmij Legacy",
      abn_jester_legacy = "Jester Legacy",
      abn_currency = "Currency",
      abn_chain = "Chain",
      abn_aim = "Aim",
      abn_stinker = "Stinker",
      abn_bug = "Bug",
      abn_martini = "Martini",
      abn_road_block = "Road Block",
      abn_lightbulb = "Lightbulb",
      abn_pawn = "Pawn",
      abn_matchstick = "Matchstick",
      abn_bomb = "Bomb",
      abn_tnt = "TNT",
      abn_cigarettes = "Cigarettes",
      abn_cowboy_hat = "Cowboy Hat",
      abn_unholy_relic = "Unholy Relic",
      abn_platano = "Platano",
      abn_cactus = "Cactus",
    }
  }
}
